#!/bin/bash
#PBS -N install_vllm
#PBS -A <project_name>
#PBS -l walltime=00:20:00
#PBS -l filesystems=home:eagle
#PBS -l select=1
#PBS -q by-gpu
#PBS -k doe

# Load required modules
module use /soft/modulefiles
module load conda

# Setup proxy
export HTTP_PROXY="http://proxy.alcf.anl.gov:3128"
export HTTPS_PROXY="http://proxy.alcf.anl.gov:3128"
export http_proxy="http://proxy.alcf.anl.gov:3128"
export https_proxy="http://proxy.alcf.anl.gov:3128"

# Create and activate conda environment
conda create -n vllm-sophia-env-072 python==3.11.9 -y
source ${CONDA_PREFIX}/etc/profile.d/conda.sh
conda activate vllm-sophia-env-072

# Install vllm
pip install vllm==0.7.2