engine:
  address:
    ifname: bond0
    type: address_by_interface
  max_workers_per_node: 1
  provider:
    account: datascience
    cpus_per_node: 32
    init_blocks: 0
    max_blocks: 2
    min_blocks: 0
    nodes_per_block: 1
    queue: debug
    scheduler_options: '#PBS -l filesystems=home:eagle'
    select_options: ngpus=4
    type: PBSProProvider
    walltime: 00:60:00
    worker_init: module load conda; conda activate /eagle/tpc/zilinghan/conda_envs/vllm_web;
      source /eagle/tpc/zilinghan/eval-web-service/construct_ray.bash
  strategy:
    max_idletime: 3600
    type: SimpleStrategy
  type: HighThroughputEngine
